#!/bin/bash
set -euo pipefail

rm -rf dist
mkdir dist
tsc source/machine.ts
cp source/machine.* dist/
node esbuild.js

coffee --compile --bare --no-header --output dist/ source/cli.coffee
BIN="dist/hera"
echo "#!/usr/bin/env node" | cat - dist/cli.js > "$BIN"
chmod +x "$BIN"
rm dist/cli.js
