#!/bin/bash
set -e

./node_modules/.bin/coffee \
  --bare \
  --no-header \
  --compile \
  --output dist/ \
  source/

# cli
mkdir -p bin
BIN="bin/hera"
echo "#!/usr/bin/env node" | cat - dist/cli.js > "$BIN"
chmod +x "$BIN"
